name: Deploy to Oracle VM

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/java-bms
            
            # Fetch the latest from all branches
            git fetch origin
            
            # Switch to the release branch and pull the latest changes
            git checkout -B release origin/release
            git pull origin release
            
            # Activate the virtual environment and install dependencies
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Restart the FastAPI service to apply changes
            sudo systemctl restart fastapi-app
